# Generated by Django 3.0.4 on 2020-03-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0004_auto_20200307_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='responseForum.InterviewResponse'),
        ),
    ]
