# Generated by Django 3.0.4 on 2020-03-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0006_auto_20200307_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='likes',
        ),
    ]
