# Generated by Django 3.0.4 on 2020-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0007_remove_interviewresponse_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
