# Generated by Django 3.0.4 on 2020-03-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0008_interviewresponse_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewresponse',
            old_name='likes',
            new_name='hits',
        ),
    ]
