# Generated by Django 3.0.4 on 2020-03-13 07:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0009_auto_20200313_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 7, 9, 28, 138800))),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responseForum.InterviewResponse')),
            ],
        ),
    ]
