# Generated by Django 3.0.4 on 2020-03-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0011_auto_20200313_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseview',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
