# Generated by Django 3.0.4 on 2020-03-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0012_auto_20200313_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseview',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseview',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
