# Generated by Django 3.0.4 on 2020-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0013_auto_20200313_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='questions',
            field=models.TextField(max_length=1000000),
        ),
    ]
