# Generated by Django 3.0.4 on 2020-03-27 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0014_auto_20200319_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='rounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
