# Generated by Django 3.0.4 on 2020-03-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0015_auto_20200327_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responseForum.InterviewResponse')),
            ],
        ),
    ]
