# Generated by Django 3.0.4 on 2020-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseForum', '0016_auto_20200328_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='questions',
            field=models.TextField(default=None, max_length=1000000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
